import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sql-Crud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="md:mx-24 lg:mx-36 mx-0 md:my-12 lg:my-8 my-0 " lang="en" data-theme="light">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
